Add support for dotfiles of domains and groups
lablup/backend.ai-client-py pull request #132
Opened 2020-09-16 08:02 UTC by yongkyunlee

Added client support for operations for domain and group dotfiles

Solving issue lablup/backend.ai#210

2020-09-17 14:18 UTC, adrysn requested changes
I think this PR looks good. However, it seems like that domain-level dotfiles are not mounted to the session container. Please refer following image. There are domain-level dotfiles, `.a` and `.Renviron`, but when I launched a session, I was unable to locate them. For group-/keypair-level dotfiles, I found no problem. (FYI, `./run.sh` is a wrapper of `backend.ai`, so you can just think it as `backend.ai`)

![image](https://user-images.githubusercontent.com/7539358/93483328-ac75a800-f93b-11ea-868b-a11eeab318ff.png)

2020-09-18 06:27 UTC, yongkyunlee commented
> I think this PR looks good. However, it seems like that domain-level dotfiles are not mounted to the session container. Please refer following image. There are domain-level dotfiles, `.a` and `.Renviron`, but when I launched a session, I was unable to locate them. For group-/keypair-level dotfiles, I found no problem. (FYI, `./run.sh` is a wrapper of `backend.ai`, so you can just think it as `backend.ai`)
> 
> ![image](https://user-images.githubusercontent.com/7539358/93483328-ac75a800-f93b-11ea-868b-a11eeab318ff.png)

There was an error in the manager, so I fixed this issue [here](https://github.com/lablup/backend.ai-manager/pull/329/commits/eb02a212c3f264b140d04598bc495c99bceb48c8).

2020-09-21 00:04 UTC, adrysn approved these changes

2020-09-21 00:04 UTC, adrysn commented
LGTM.

2020-09-21 02:04 UTC, merged